[build-system]
requires = ["meson", "meson-python", "numpy"]
build-backend = "mesonpy"

[project]
name = "pyhwm2014"
version = "0.1.0"
description = "Python wrapper for HWM14."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy", "seaborn"]
